import Head from 'next/head';
import { useAppBridge } from '@/hooks';
import UserInfo from '@/components/UserInfo';
import Example from '@/components/Example';
import StoryGenerationForm from '@/components/StoryGenerationForm';
import { AppLayout, StoryblokIcon } from '@storyblok/mui';
import { Stack, Typography } from '@mui/material';

export default function Home() {
	const { completed } = useAppBridge({ type: 'space-plugin', oauth: true });

	return (
		<>
			<Head>
				<title>Storyblok Next Tool Starter</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main>
				{completed && (
					<AppLayout
						title="AI Story Generator"
						subtitle="Generate Storyblok stories from screenshots"
						icon={<StoryblokIcon fontSize="small" />}
					>
						<Stack spacing={3}>
							<Typography color="success.main" fontWeight={600}>
								Authenticated
							</Typography>
						<StoryGenerationForm />
						<UserInfo />
						<Example />
						</Stack>
					</AppLayout>
				)}
			</main>
		</>
	);
}
