// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokRichtext, StoryblokMultilink } from '../storyblok.d.ts';
export interface Button {
  text?: string;
  link: StoryblokMultilink;
  color: "" | "primary" | "secondary";
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface Card {
  icon?: StoryblokAsset;
  description?: StoryblokRichtext;
  component: "card";
  _uid: string;
  [k: string]: unknown;
}

export interface Cards {
  description?: StoryblokRichtext;
  cards?: Card[];
  component: "cards";
  _uid: string;
  [k: string]: unknown;
}

export interface Hero {
  image?: StoryblokAsset;
  imagePadding?: boolean;
  backgroundColor?: "" | "white" | "beige" | "grey" | "purple" | "orange" | "yellow" | "green" | "pink" | "blue";
  textAlignment?: "" | "left" | "right" | "center";
  description?: StoryblokRichtext;
  buttons?: Button[];
  component: "hero";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Button | Card | Cards | Hero | Page | Tab | Tabs | TeamMember | TeamMembers | Testimonial | Testimonials)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Tab {
  title?: string;
  content?: (
    | Button
    | Card
    | Cards
    | Hero
    | Page
    | Tab
    | Tabs
    | TeamMember
    | TeamMembers
    | Testimonial
    | Testimonials
  )[];
  component: "tab";
  _uid: string;
  [k: string]: unknown;
}

export interface Tabs {
  description?: StoryblokRichtext;
  tabs?: Tab[];
  component: "tabs";
  _uid: string;
  [k: string]: unknown;
}

export interface TeamMember {
  name?: string;
  title?: string;
  image?: StoryblokAsset;
  backgroundColor?: "" | "white" | "beige" | "grey" | "purple" | "orange" | "yellow" | "green" | "pink";
  component: "teamMember";
  _uid: string;
  [k: string]: unknown;
}

export interface TeamMembers {
  teamMembers?: (ISbStoryData<TeamMember> | string)[];
  description?: StoryblokRichtext;
  component: "teamMembers";
  _uid: string;
  [k: string]: unknown;
}

export interface Testimonial {
  quote?: string;
  name?: string;
  title?: string;
  image?: StoryblokAsset;
  imageBackgroundColor?: "" | "white" | "beige" | "grey" | "purple" | "orange" | "yellow" | "green" | "pink" | "blue";
  component: "testimonial";
  _uid: string;
  [k: string]: unknown;
}

export interface Testimonials {
  title?: string;
  description?: string;
  testimonials?: Testimonial[];
  component: "testimonials";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Page | TeamMember;
